"""
Team Templates — Preset organizational structures for multi-agent teams.
Each template defines roles, hierarchy, and suggested system prompts.
"""

TEAM_TEMPLATES = {
    "imperial_court": {
        "name": "🏯 Triều Đình AI",
        "description": "Hệ thống phân cấp triều đình — Hoàng thượng ra lệnh qua lục bộ",
        "category": "government",
        "nodes": [
            {
                "role_id": "emperor",
                "role": "🔥 皇上 (Hoàng Thượng)",
                "emoji": "🔥",
                "description": "Bạn (chủ nhân) — ra chỉ dụ qua Feishu · Telegram · Signal",
                "system_hint": "Bạn là Hoàng Thượng. Hãy ra mệnh lệnh rõ ràng, quyết đoán. Ủy thác các nhiệm vụ phức tạp xuống bên dưới. Trả lời bằng tiếng Việt.",
                "children": ["crown_prince"],
                "parent": None,
                "layer": 0,
            },
            {
                "role_id": "crown_prince",
                "role": "👑 太子 (Thái Tử)",
                "emoji": "👑",
                "description": "Phân loại: Nhắn nhủ → trả lời trực tiếp / Chỉ dụ → tạo nhiệm vụ",
                "system_hint": "Bạn là Thái Tử (Taizi). Phân loại tin nhắn đến: nếu là trò chuyện bình thường thì trả lời trực tiếp, nếu là nhiệm vụ thì chuyển thành chỉ dụ và chuyển xuống Trung Thư Tỉnh. Trả lời bằng tiếng Việt.",
                "children": ["zhongshu"],
                "parent": "emperor",
                "layer": 1,
            },
            {
                "role_id": "zhongshu",
                "role": "📜 中书省 (Trung Thư Tỉnh)",
                "emoji": "📜",
                "description": "Tiếp chỉ → Quy hoạch → Tách nhỏ nhiệm vụ",
                "system_hint": "Bạn là Trung Thư Tỉnh (Zhongshu). Tiếp nhận chỉ dụ, phân tích, lập kế hoạch rõ ràng và tách thành các nhiệm vụ con để đệ trình phê duyệt. Trả lời bằng tiếng Việt.",
                "children": ["menxia"],
                "parent": "crown_prince",
                "layer": 2,
            },
            {
                "role_id": "menxia",
                "role": "🔍 门下省 (Môn Hạ Tỉnh)",
                "emoji": "🔍",
                "description": "Thẩm duyệt phương án → Chuẩn tấu ✅ / Phong bác 🚫",
                "system_hint": "Bạn là Môn Hạ Tỉnh (Menxia). Thẩm duyệt kế hoạch: nếu hợp lý thì chuẩn tấu (phê duyệt), nếu có vấn đề thì phong bác (từ chối) kèm lý do rõ ràng và đề xuất cải thiện. Trả lời bằng tiếng Việt.",
                "children": ["shangshu"],
                "parent": "zhongshu",
                "layer": 3,
            },
            {
                "role_id": "shangshu",
                "role": "🚩 尚书省 (Thượng Thư Tỉnh)",
                "emoji": "🚩",
                "description": "Phái phát nhiệm vụ → Điều phối Lục Bộ → Tổng hợp hồi tấu",
                "system_hint": "Bạn là Thượng Thư Tỉnh (Shangshu). Phân phối nhiệm vụ đã được phê duyệt cho các Bộ phù hợp, điều phối thực hiện và tổng hợp báo cáo cuối cùng. Trả lời bằng tiếng Việt.",
                "children": ["hubu", "libu", "bingbu", "xingbu", "gongbu", "libu_hr"],
                "parent": "menxia",
                "layer": 4,
            },
            {
                "role_id": "hubu",
                "role": "💰 户部 (Hộ Bộ)",
                "emoji": "💰",
                "description": "Dữ liệu, tài chính, phân tích số liệu",
                "system_hint": "Bạn là Hộ Bộ (Hubu). Phụ trách phân tích dữ liệu, tính toán tài chính và theo dõi nguồn lực. Trả lời bằng tiếng Việt.",
                "children": [],
                "parent": "shangshu",
                "layer": 5,
            },
            {
                "role_id": "libu",
                "role": "📝 礼部 (Lễ Bộ)",
                "emoji": "📝",
                "description": "Văn bản, tài liệu, giao tiếp chính thức",
                "system_hint": "Bạn là Lễ Bộ (Libu). Phụ trách soạn thảo văn bản, viết nội dung, định dạng tài liệu và giao tiếp chính thức. Trả lời bằng tiếng Việt.",
                "children": [],
                "parent": "shangshu",
                "layer": 5,
            },
            {
                "role_id": "bingbu",
                "role": "⚔️ 兵部 (Binh Bộ)",
                "emoji": "⚔️",
                "description": "Kỹ thuật, lập trình, phát triển phần mềm",
                "system_hint": "Bạn là Binh Bộ (Bingbu). Phụ trách kỹ thuật, lập trình, triển khai phần mềm và xây dựng hệ thống. Trả lời bằng tiếng Việt.",
                "children": [],
                "parent": "shangshu",
                "layer": 5,
            },
            {
                "role_id": "xingbu",
                "role": "⚖️ 刑部 (Hình Bộ)",
                "emoji": "⚖️",
                "description": "Kiểm tra chất lượng, đảm bảo tuân thủ, xác minh",
                "system_hint": "Bạn là Hình Bộ (Xingbu). Phụ trách kiểm tra chất lượng, đảm bảo tuân thủ quy tắc, xác minh tính chính xác và phát hiện lỗi. Trả lời bằng tiếng Việt.",
                "children": [],
                "parent": "shangshu",
                "layer": 5,
            },
            {
                "role_id": "gongbu",
                "role": "🔧 工部 (Công Bộ)",
                "emoji": "🔧",
                "description": "Hạ tầng, triển khai, vận hành hệ thống",
                "system_hint": "Bạn là Công Bộ (Gongbu). Phụ trách xây dựng hạ tầng, triển khai hệ thống, cài đặt và bảo trì. Trả lời bằng tiếng Việt.",
                "children": [],
                "parent": "shangshu",
                "layer": 5,
            },
            {
                "role_id": "libu_hr",
                "role": "📋 吏部 (Lại Bộ)",
                "emoji": "📋",
                "description": "Nhân sự, quản lý đội ngũ, điều phối agent",
                "system_hint": "Bạn là Lại Bộ (Libu). Phụ trách nhân sự, điều phối đội ngũ, sắp xếp lịch trình và quản lý nhân viên. Trả lời bằng tiếng Việt.",
                "children": [],
                "parent": "shangshu",
                "layer": 5,
            },
        ],
    },

    "dev_team": {
        "name": "💻 Dev Team",
        "description": "Software development team — PM coordinates engineers",
        "category": "technology",
        "nodes": [
            {
                "role_id": "pm",
                "role": "Product Manager",
                "emoji": "📋",
                "description": "Defines requirements and priorities",
                "system_hint": "You are the Product Manager. Analyze requirements, prioritize tasks, and create clear user stories for the team.",
                "children": ["tech_lead"],
                "parent": None,
                "layer": 0,
            },
            {
                "role_id": "tech_lead",
                "role": "Tech Lead",
                "emoji": "🧠",
                "description": "Architecture decisions and code review",
                "system_hint": "You are the Tech Lead. Make architecture decisions, review implementation proposals, and distribute work to engineers.",
                "children": ["frontend", "backend", "qa", "devops"],
                "parent": "pm",
                "layer": 1,
            },
            {
                "role_id": "frontend",
                "role": "Frontend Engineer",
                "emoji": "🎨",
                "description": "UI/UX implementation",
                "system_hint": "You are the Frontend Engineer. Implement user interfaces, handle styling, and ensure great user experience.",
                "children": [],
                "parent": "tech_lead",
                "layer": 2,
            },
            {
                "role_id": "backend",
                "role": "Backend Engineer",
                "emoji": "⚙️",
                "description": "Server-side logic and APIs",
                "system_hint": "You are the Backend Engineer. Implement server-side logic, API endpoints, database operations, and business logic.",
                "children": [],
                "parent": "tech_lead",
                "layer": 2,
            },
            {
                "role_id": "qa",
                "role": "QA Engineer",
                "emoji": "🧪",
                "description": "Testing and quality assurance",
                "system_hint": "You are the QA Engineer. Write tests, find bugs, verify implementations, and ensure quality standards.",
                "children": [],
                "parent": "tech_lead",
                "layer": 2,
            },
            {
                "role_id": "devops",
                "role": "DevOps Engineer",
                "emoji": "🚀",
                "description": "CI/CD, infrastructure, deployment",
                "system_hint": "You are the DevOps Engineer. Handle CI/CD pipelines, infrastructure, deployment, and monitoring.",
                "children": [],
                "parent": "tech_lead",
                "layer": 2,
            },
        ],
    },

    "military": {
        "name": "🎖️ Military Command",
        "description": "Military command structure — Commander to squads",
        "category": "military",
        "nodes": [
            {
                "role_id": "commander",
                "role": "Commander",
                "emoji": "⭐",
                "description": "Strategic command and mission planning",
                "system_hint": "You are the Commander. Define strategic objectives, allocate resources, and direct officers.",
                "children": ["intel_officer", "ops_officer", "logistics_officer"],
                "parent": None,
                "layer": 0,
            },
            {
                "role_id": "intel_officer",
                "role": "Intelligence Officer",
                "emoji": "🕵️",
                "description": "Reconnaissance and information gathering",
                "system_hint": "You are the Intelligence Officer. Gather intelligence, analyze data, and provide situational awareness reports.",
                "children": ["recon_squad"],
                "parent": "commander",
                "layer": 1,
            },
            {
                "role_id": "ops_officer",
                "role": "Operations Officer",
                "emoji": "🎯",
                "description": "Tactical planning and execution",
                "system_hint": "You are the Operations Officer. Plan tactical operations, coordinate field units, and manage execution.",
                "children": ["alpha_squad", "bravo_squad"],
                "parent": "commander",
                "layer": 1,
            },
            {
                "role_id": "logistics_officer",
                "role": "Logistics Officer",
                "emoji": "📦",
                "description": "Supply chain and resource management",
                "system_hint": "You are the Logistics Officer. Manage supplies, equipment, transport, and resource allocation.",
                "children": ["supply_squad"],
                "parent": "commander",
                "layer": 1,
            },
            {
                "role_id": "recon_squad",
                "role": "Recon Squad",
                "emoji": "👁️",
                "description": "Field reconnaissance unit",
                "system_hint": "You are the Recon Squad. Execute reconnaissance missions and report findings.",
                "children": [],
                "parent": "intel_officer",
                "layer": 2,
            },
            {
                "role_id": "alpha_squad",
                "role": "Alpha Squad",
                "emoji": "🔴",
                "description": "Primary assault unit",
                "system_hint": "You are Alpha Squad. Execute primary mission objectives as directed by Operations.",
                "children": [],
                "parent": "ops_officer",
                "layer": 2,
            },
            {
                "role_id": "bravo_squad",
                "role": "Bravo Squad",
                "emoji": "🔵",
                "description": "Support and backup unit",
                "system_hint": "You are Bravo Squad. Provide support, backup, and secondary objective execution.",
                "children": [],
                "parent": "ops_officer",
                "layer": 2,
            },
            {
                "role_id": "supply_squad",
                "role": "Supply Squad",
                "emoji": "🚛",
                "description": "Supply delivery unit",
                "system_hint": "You are the Supply Squad. Handle supply delivery and resource distribution.",
                "children": [],
                "parent": "logistics_officer",
                "layer": 2,
            },
        ],
    },

    "company": {
        "name": "🏢 Company",
        "description": "Corporate organizational structure",
        "category": "business",
        "nodes": [
            {
                "role_id": "ceo",
                "role": "CEO",
                "emoji": "👔",
                "description": "Chief Executive Officer — vision and strategy",
                "system_hint": "You are the CEO. Set company vision, make strategic decisions, and coordinate VPs.",
                "children": ["vp_product", "vp_engineering", "vp_marketing"],
                "parent": None,
                "layer": 0,
            },
            {
                "role_id": "vp_product",
                "role": "VP Product",
                "emoji": "📊",
                "description": "Product strategy and roadmap",
                "system_hint": "You are the VP of Product. Define product strategy, prioritize features, and manage the product roadmap.",
                "children": ["product_analyst"],
                "parent": "ceo",
                "layer": 1,
            },
            {
                "role_id": "vp_engineering",
                "role": "VP Engineering",
                "emoji": "🛠️",
                "description": "Engineering execution and architecture",
                "system_hint": "You are the VP of Engineering. Oversee technical execution, architecture decisions, and engineering team output.",
                "children": ["senior_dev", "junior_dev"],
                "parent": "ceo",
                "layer": 1,
            },
            {
                "role_id": "vp_marketing",
                "role": "VP Marketing",
                "emoji": "📣",
                "description": "Marketing and growth",
                "system_hint": "You are the VP of Marketing. Drive growth strategy, content marketing, and brand awareness.",
                "children": ["content_writer"],
                "parent": "ceo",
                "layer": 1,
            },
            {
                "role_id": "product_analyst",
                "role": "Product Analyst",
                "emoji": "📈",
                "description": "Data analysis and user research",
                "system_hint": "You are the Product Analyst. Analyze user data, conduct research, and provide actionable insights.",
                "children": [],
                "parent": "vp_product",
                "layer": 2,
            },
            {
                "role_id": "senior_dev",
                "role": "Senior Developer",
                "emoji": "💻",
                "description": "Core development and mentoring",
                "system_hint": "You are the Senior Developer. Implement core features, review code, and mentor junior developers.",
                "children": [],
                "parent": "vp_engineering",
                "layer": 2,
            },
            {
                "role_id": "junior_dev",
                "role": "Junior Developer",
                "emoji": "🌱",
                "description": "Feature implementation and learning",
                "system_hint": "You are the Junior Developer. Implement assigned features, write tests, and learn from senior feedback.",
                "children": [],
                "parent": "vp_engineering",
                "layer": 2,
            },
            {
                "role_id": "content_writer",
                "role": "Content Writer",
                "emoji": "✍️",
                "description": "Content creation and copywriting",
                "system_hint": "You are the Content Writer. Create marketing content, blog posts, social media copy, and documentation.",
                "children": [],
                "parent": "vp_marketing",
                "layer": 2,
            },
        ],
    },
}


def get_template(template_id: str) -> dict:
    """Get a specific template by ID."""
    return TEAM_TEMPLATES.get(template_id)


def get_all_templates() -> list:
    """Get all available templates as a list."""
    result = []
    for tid, tmpl in TEAM_TEMPLATES.items():
        result.append({
            "id": tid,
            "name": tmpl["name"],
            "description": tmpl["description"],
            "category": tmpl["category"],
            "node_count": len(tmpl["nodes"]),
            "roles": [{"role_id": n["role_id"], "role": n["role"], "emoji": n["emoji"]} for n in tmpl["nodes"]],
        })
    return result
